services:
  test:
    image: codercom/code-server:latest
    command: /source --auth none --disable-telemetry --disable-update-check --port 8888
    container_name: vscode
    ports:
      - "8888:8888"
    volumes:
      - ./src/test/fixtures/workspace:/source
      - ./src/test/fixtures/workspace/sbin:/usr/local/sbin