name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress:
    name: vscode-cadence Cypress End to End tests
    #timeout-minutes: 30
    runs-on: macos-12
    #container: cypress/browsers:node12.18.3-chrome87-ff82
    #container: cypress/browsers:node16.14.2-slim-chrome103-ff102 #use arm64 arch on Apple M1 chips when running locally
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Setup docker for macos
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Install dependencies
        run: npm ci

      - name: Package
        run: npm run package-test

      - name: Start vscode Docker Container
        run: npm run vscode-start

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          wait-on: 'http://localhost:8888'
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Record Cypress
      #  run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}

      #- mame: End-to-end tests
      #  run: npm run e2e-test
      
      #- name: Cypress run
      #  uses: cypress-io/github-action@v4
      #  with:
      #    start: npm run dev:emulator
      #    wait-on: http://localhost:8888


  #tests:
  #  name: "Running Tests"
  #  runs-on: macos-12    # Can run flow-cli but all tests fail
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v3
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #    - name: setup-docker
  #      uses: docker-practice/actions-setup-docker@v1
  #    - name: Install dependencies
  #      run: npm ci
  #    - name: "Run end-to-end tests"
  #      run: npm run e2e-test

  #tests:
  #  name: "Running Tests"
  #  runs-on: ubuntu-latest      # Can't access flow-cli
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #    - run: npm ci
  #    #- name: "Unit Tests"
  #    #  run: npm run unit-test
  #    - name: "End-to-end Tests"
  #      run: npm run e2e-test
