name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: "Running Tests"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      #- name: setup-docker
      #  uses: docker-practice/actions-setup-docker@v1
      - name: Install dependencies
        run: brew install flow-cli
        run: npm ci
      - name: "End-to-end Tests"
        run: npm run e2e-test

  #tests:
  #  name: "Running Tests"
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v2
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #    - run: npm ci
      #- name: "Unit Tests"
      #  run: npm run unit-test
  #    - name: "End-to-end Tests"
  #      run: npm run e2e-test
