name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: "Running Tests"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install vscode
      - run: brew install --cask visual-studio-code
      - name: Install Dependencies
      - run: npm ci
      - name: Install flow-cli
      - run: brew install flow-cli
      #- name: "Unit Tests"
      #  run: npm run unit-test
      - name: "End-to-end Tests"
        run: npm run e2e-test-action

  #tests:
  #  name: "Running Tests"
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v2
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #    - run: npm ci
      #- name: "Unit Tests"
      #  run: npm run unit-test
  #    - name: "End-to-end Tests"
  #      run: npm run e2e-test
