name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  #standard:
  #  name: "Code Style Standard"
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v2
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #    - run: npm ci
  #    - run: npm run lint

  tests:
    name: "Running Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: "Unit Tests"
        run: npm run unit-test
      - name: "End-to-end Tests"
        run: npm run e2e-test
        #uses: cypress-io/github-action@v2
        #with:
        #  build: npm run package-test
        #  start: npm run vscode-start
        #  wait-on: http://localhost:8888