name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

ubuntu-setup: &ubuntu
  name: Build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

jobs:
  linter:
    name: "Code Style Standard"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run lint

  build: *ubuntu
      - name: Package
        run: npm run package

  unittest:
    needs: build
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Package
        run: npm run package-test

      - name: Unit Tests
        run: npm run unit-test

  integration:
    needs: build
    runs-on: windows-latest
    name: Integration Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Integration Tests
        run: npm run integration-test

  cypress:
    needs: [unittest, integration]
    name: Cypress End to End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Package
        run: npm run package-test

      - name: Start vscode Docker Container
        run: npm run vscode-start

      - name: Wait for docker container
        run: pip install wait-for-it && wait-for-it --service http://localhost:8888

      - name: Install flow-cli
        run: docker exec vscode sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          wait-on: 'http://localhost:8888'
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
