name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress:
    name: vscode-cadence Cypress End to End tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome103-ff102 #use arm64 arch on Apple M1 chips when running locally
    steps:
      - name: Install build dependencies (mostly for sqlite on ARM)
        run: apt-get update -y && apt-get install build-essential -y

      - name: Install Flow CLI
        # run: |
        #   sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" &&
        #   echo "/root/.local/bin:/github/home/.local/bin" >> $GITHUB_PATH
        run: |
          sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" &&
          echo "/root/.local/bin:/github/home/.local/bin" >> $GITHUB_PATH &&
          echo $HOME &&
          ls -l $HOME/.local/bin &&
          chmod a+r $HOME/.local/bin/flow &&
          ls -l $HOME/.local/bin

      - name: Checkout
        uses: actions/checkout@v3

      - name: Package
        run: npm run package-test

      - name: VS Code Docker
        run: npm run vscode-start

      #- name: chmod subdirs to bypass lerna exec access permission issues
      #  run: |
      #    pwd &&
      #    ls -l &&
      #    chmod -R 777 api &&
      #    chmod -R 777 web &&
      #    chmod -R 777 cadence/tests &&
      #    ls -l

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev:emulator
          #wait-on: http://localhost:3001


  #tests:
  #  name: "Running Tests"
  #  runs-on: macos-12    # Can run flow-cli but all tests fail
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v3
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #    - name: setup-docker
  #      uses: docker-practice/actions-setup-docker@v1
  #    - name: Install dependencies
  #      run: npm ci
  #    - name: "Run end-to-end tests"
  #      run: npm run e2e-test

  #tests:
  #  name: "Running Tests"
  #  runs-on: ubuntu-latest      # Can't access flow-cli
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #    - run: npm ci
  #    #- name: "Unit Tests"
  #    #  run: npm run unit-test
  #    - name: "End-to-end Tests"
  #      run: npm run e2e-test
