name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    name: "Running Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      #- name: "Unit Tests"
      #  run: npm run unit-test
      - name: "Enable flow cmd"
        run: docker exec vscode sudo chmod +x /usr/local/bin/flow
      - name: "test flow"
        run: flow
      - name: "End-to-end Tests"
        run: npm run e2e-test
